# Dependencies
#markdown:         redcarpet -- depricated
highlighter:      rouge #pygments -- not supported option

# Permalinks
permalink:        pretty
#relative_permalinks: true -- depricated feature

# Setup
title:            Bram Van Moorter
tagline:          'Blog'
description:      'My blog'
url:              http://www.nina.no/english/Contact/Employees/Employee-info/AnsattID/14700
baseurl:          /
image:            "http://foto.nina.no/gs/handler/getmedia.ashx?moid=5&dt=2&g=3"

author:
  name:           'Bram Van Moorter'
  url:            http://www.nina.no/english/Contact/Employees/Employee-info/AnsattID/14700
  image:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ninbrm
