# Dependencies
#markdown:         redcarpet -- depricated
highlighter:      rouge #pygments -- not supported option

# Permalinks
permalink:        pretty
#relative_permalinks: true -- depricated feature

# Setup
title:            Bram Van Moorter
tagline:          'Blog'
description:      '<a href="http://www.nina.no/english/Contact/Employees/Employee-info/AnsattID/14700" target="_blank">Bram Van Moorter</a> blog. '
url:              http://www.nina.no/english/Contact/Employees/Employee-info/AnsattID/14700
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
